version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.routers.react-app.entrypoints=http
      - traefik.http.routers.react-app.rule=Host(`moyoboza.com`)
      - traefik.http.services.react-app.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true
