version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static-assets:/usr/share/nginx/html
    ports:
      - 3000:3000
    networks:
      - traefik-public

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static-assets:/usr/share/nginx/html
    ports:
      - 8000:80
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

volumes:
  static-assets: