version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static-assets:/usr/share/nginx/html
    ports:
      - 3000:3000
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.routers.react-app.entrypoints=http
      - traefik.http.routers.react-app.rule=Host(`moyoboza.com`)
      - traefik.http.services.react-app.loadbalancer.server.port=3000


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static-assets:/usr/share/nginx/html
    ports:
      - 8000:80
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

volumes:
  static-assets:
